### ISSUE TITLE
arrays show zeroes in python

### ISSUE THREAD

**Issue by MaameBoamahPoku** [danielm09/rf_youtube#1]
hello @danielm09 
I have tried implementing svm using your video on Random forest. I tried to display the arrays of my bands but they appeared as zeroes and no data values. I would be grateful if you could guide me on the issue. I have attached snips of my codes and the results for your attention. thank you

![svm2](https://user-images.githubusercontent.com/91562461/152033955-0f0b718b-e474-4ca7-a290-ac70065bb7fb.JPG)
![svm1](https://user-images.githubusercontent.com/91562461/152033962-c2cbdb7e-baf5-4e60-bb57-2602dd5a5ff3.JPG)
![svm4](https://user-images.githubusercontent.com/91562461/152033967-4e371610-03e8-4adc-af3b-9feeb6d5ddf0.JPG)
![svm3](https://user-images.githubusercontent.com/91562461/152033970-9bf71be1-0e7a-4d80-bc5f-eafc8f5a824f.JPG)

**Comment by danielm09** [comment]
Hi @MaameBoamahPoku 

Looking at the code snippet you provided, I have 2 things I think you could check.
First, the nodata value you're getting when you print the array might be explained by the first and last pixels being outside the mask. This can happen if you cut the image using some mask. What I mean is, the edge of the image might contain nodata and the actual data can be in the center. 

Second, I'm not sure if Landsat values are provided in a scale from -10000 to 10000 or -1 to 1. If that's the case (-1 to 1), you might want to change the dtype to float, as follows:
`test = pd.DataFrame(array, dtype='float32')`

I hope this could help.
